GET http://localhost:3001/api/notes/

###
DELETE  http://localhost:3001/api/notes/607c77a057692a2df3bc7b7e

###
PUT  http://localhost:3001/api/notes/608964cd33cbf800158873fe
Content-Type: application/json

{
  "content": "hello this has been updated2!!",
  "important": false
}