GET http://localhost:3001/api/notes/

###
DELETE  http://localhost:3001/api/notes/60788ad2ca578610f1a318e1

###
PUT  http://localhost:3001/api/notes/6075c897c7f7d31f6f58131c
Content-Type: application/json

{
  "content": "hello",
  "important": false
}