GET http://localhost:3001/api/notes/

###
DELETE  http://localhost:3001/api/notes/607c77a057692a2df3bc7b7e

###
PUT  http://localhost:3001/api/notes/608964cd33cbf800158873fe
Content-Type: application/json

{
  "content": "hello this has been updated2!!",
  "important": false
}

###
GET http://localhost:3001/api/users

###

POST http://localhost:3001/api/users
Content-Type: application/json

{
    "notes": [],
    "username": "root",
    "name": "Superuser",
    "password": "salainen"
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "user id of the note creator is at the start sent along the req",
  "important": true,
  "userId": "608faa428cc22a37555e6c04"
}