POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "test title",
  "author": "test author",
  "url": "test url",
  "likes": 2,
  "userId": "6091121804a7f961b64ebcd9"
}

###
GET http://localhost:3001/api/blogs

###
DELETE http://localhost:3001/api/blogs/608c07cdfe18b41364a1071a

###
PUT  http://localhost:3001/api/blogs/608c0725b975bd126821a466
Content-Type: application/json

{
    "title": "body.tiffle",
    "author": "bod3y.author",
    "url": "body.url",
    "likes": "522"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "test username 2",
  "name": "tester 2",
  "password": "pass2"
}