POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "test title last",
  "author": "test author",
  "url": "test url",
  "likes": 10
}

###
GET http://localhost:3001/api/blogs